# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastrocarro.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as conector

# class Veiculo:
#     def __init__(self, placa, marca, modelo, ano, renavam):
#         self.placa = placa
#         self.marca = marca
#         self.modelo = modelo
#         self.ano = ano
#         self.renavam = renavam

class Ui_Cadcarro(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1075, 449)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 40, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 150, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setIndent(3)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 190, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setIndent(3)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(80, 270, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setIndent(3)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(80, 230, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setIndent(3)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(80, 310, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setIndent(3)
        self.label_8.setObjectName("label_8")
        self.linePlate = QtWidgets.QLineEdit(Dialog)
        self.linePlate.setGeometry(QtCore.QRect(260, 160, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.linePlate.setFont(font)
        self.linePlate.setMouseTracking(True)
        self.linePlate.setStyleSheet("alternate-background-color: rgb(0, 170, 255);\n"
"gridline-color: rgb(0, 170, 255);")
        self.linePlate.setText("")
        self.linePlate.setObjectName("linePlate")
        self.lineBrand = QtWidgets.QLineEdit(Dialog)
        self.lineBrand.setGeometry(QtCore.QRect(260, 200, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineBrand.setFont(font)
        self.lineBrand.setMouseTracking(True)
        self.lineBrand.setToolTip("")
        self.lineBrand.setStyleSheet("alternate-background-color: rgb(0, 170, 255);\n"
"gridline-color: rgb(0, 170, 255);")
        self.lineBrand.setText("")
        self.lineBrand.setObjectName("lineBrand")
        self.lineModel = QtWidgets.QLineEdit(Dialog)
        self.lineModel.setGeometry(QtCore.QRect(260, 240, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineModel.setFont(font)
        self.lineModel.setMouseTracking(True)
        self.lineModel.setToolTip("")
        self.lineModel.setStyleSheet("alternate-background-color: rgb(0, 170, 255);\n"
"gridline-color: rgb(0, 170, 255);")
        self.lineModel.setText("")
        self.lineModel.setObjectName("lineModel")
        self.lineYear = QtWidgets.QLineEdit(Dialog)
        self.lineYear.setGeometry(QtCore.QRect(260, 280, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineYear.setFont(font)
        self.lineYear.setMouseTracking(True)
        self.lineYear.setToolTip("")
        self.lineYear.setStyleSheet("alternate-background-color: rgb(0, 170, 255);\n"
"gridline-color: rgb(0, 170, 255);")
        self.lineYear.setText("")
        self.lineYear.setObjectName("lineYear")
        self.lineRenavam = QtWidgets.QLineEdit(Dialog)
        self.lineRenavam.setGeometry(QtCore.QRect(260, 320, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineRenavam.setFont(font)
        self.lineRenavam.setMouseTracking(True)
        self.lineRenavam.setToolTip("")
        self.lineRenavam.setStyleSheet("alternate-background-color: rgb(0, 170, 255);\n"
"gridline-color: rgb(0, 170, 255);")
        self.lineRenavam.setText("")
        self.lineRenavam.setObjectName("lineRenavam")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(50, 370, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("alternate-background-color: rgb(85, 170, 255);")
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 370, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("alternate-background-color: rgb(85, 170, 255);")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 370, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("alternate-background-color: rgb(85, 170, 255);")
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(670, 210, 231, 271))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(144)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 85, 0);\n"
"alternate-background-color: rgb(85, 85, 255);")
        self.label_14.setObjectName("label_14")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # Conectar o botão "Cadastrar" ao método addCarro
        self.pushButton.clicked.connect(self.addCarro)

        # Configurar banco de dados
        self.setupDatabase()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">CADASTRO DE VEÍCULOS</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Placa:"))
        self.label_3.setText(_translate("Dialog", "Marca:"))
        self.label_4.setText(_translate("Dialog", "Ano:"))
        self.label_5.setText(_translate("Dialog", "Modelo:"))
        self.label_8.setText(_translate("Dialog", "Renavam:"))
        self.linePlate.setToolTip(_translate("Dialog", "Informe uma placa padrão Mercosul: AAA-1A11"))
        self.linePlate.setPlaceholderText(_translate("Dialog", "Digite aqui"))
        self.lineBrand.setPlaceholderText(_translate("Dialog", "Digite aqui"))
        self.lineModel.setPlaceholderText(_translate("Dialog", "Digite aqui"))
        self.lineYear.setPlaceholderText(_translate("Dialog", "Digite aqui"))
        self.lineRenavam.setPlaceholderText(_translate("Dialog", "Digite aqui"))
        self.pushButton.setWhatsThis(_translate("Dialog", "<html><head/><body><p>xxxxx</p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Cadastrar"))
        self.pushButton_2.setWhatsThis(_translate("Dialog", "<html><head/><body><p>xxxxx</p></body></html>"))
        self.pushButton_2.setText(_translate("Dialog", "Cancelar"))
        self.pushButton_3.setWhatsThis(_translate("Dialog", "<html><head/><body><p>xxxxx</p></body></html>"))
        self.pushButton_3.setText(_translate("Dialog", "Limpar"))
        self.label_14.setText(_translate("Dialog", "v"))

    def setupDatabase(self):
        # Configura o banco de dados
        self.conn = conector.connect('pneusfrota.db')
        self.conn.execute('PRAGMA foreign_keys = on')
        self.cursor = self.conn.cursor()

        # Cria a tabela Carro se ela não existir
        comando = '''CREATE TABLE IF NOT EXISTS Carro (
            placa TEXT NOT NULL,
            marca TEXT NOT NULL,
            modelo TEXT NOT NULL,
            ano DATE NOT NULL,
            renavam TEXT NOT NULL,
            PRIMARY KEY (placa)
        );'''
        self.cursor.execute(comando)
        self.conn.commit()

    def addCarro(self):
        # Método para adicionar um carro no banco de dados
        placa = self.linePlate.text()
        marca = self.lineBrand.text()
        modelo = self.lineModel.text()
        ano = self.lineYear.text()
        renavam = self.lineRenavam.text()

        if placa and marca and modelo and ano and renavam:
            comando = "INSERT INTO Carro (placa, marca, modelo, ano, renavam) VALUES (?, ?, ?, ?, ?)"
            try:
                self.cursor.execute(comando, (placa, marca, modelo, ano, renavam))
                self.conn.commit()
                QtWidgets.QMessageBox.information(None, 'Sucesso', 'Carro cadastrado com sucesso!')
            except conector.IntegrityError:
                QtWidgets.QMessageBox.warning(None, 'Erro', 'Erro ao cadastrar o carro. Verifique se a placa já está cadastrada.')
        else:
            QtWidgets.QMessageBox.warning(None, 'Erro', 'Todos os campos são obrigatórios!')
