from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as conector

class Ui_Cadpneu(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1075, 501)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 40, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 150, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setIndent(3)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(80, 240, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setIndent(3)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(80, 200, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setIndent(3)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(80, 280, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_10.setTextFormat(QtCore.Qt.RichText)
        self.label_10.setIndent(3)
        self.label_10.setObjectName("label_10")
        self.comboBoxTyrePos = QtWidgets.QComboBox(Dialog)
        self.comboBoxTyrePos.setGeometry(QtCore.QRect(260, 210, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxTyrePos.setFont(font)
        self.comboBoxTyrePos.setStyleSheet("alternate-background-color: rgb(0, 170, 255);\n"
"gridline-color: rgb(0, 170, 255);")
        self.comboBoxTyrePos.setObjectName("comboBoxTyrePos")
        self.comboBoxTyrePos.addItem("")
        self.comboBoxTyrePos.addItem("")
        self.comboBoxTyrePos.addItem("")
        self.comboBoxTyrePos.addItem("")
        self.comboBoxTyrePos.addItem("")
        self.comboBoxTyrePos.addItem("")
        self.doubleSpinBoxTyreGroove = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBoxTyreGroove.setGeometry(QtCore.QRect(260, 291, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxTyreGroove.setFont(font)
        self.doubleSpinBoxTyreGroove.setStyleSheet("alternate-background-color: rgb(0, 170, 255);\n"
"gridline-color: rgb(0, 170, 255);")
        self.doubleSpinBoxTyreGroove.setObjectName("doubleSpinBoxTyreGroove")
        self.lineTyreDOT = QtWidgets.QLineEdit(Dialog)
        self.lineTyreDOT.setGeometry(QtCore.QRect(260, 250, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineTyreDOT.setFont(font)
        self.lineTyreDOT.setMouseTracking(True)
        self.lineTyreDOT.setStyleSheet("alternate-background-color: rgb(0, 170, 255);\n"
"gridline-color: rgb(0, 170, 255);")
        self.lineTyreDOT.setText("")
        self.lineTyreDOT.setObjectName("lineTyreDOT")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(60, 410, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("alternate-background-color: rgb(85, 170, 255);")
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(80, 335, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_13.setTextFormat(QtCore.Qt.RichText)
        self.label_13.setIndent(3)
        self.label_13.setObjectName("label_13")
        self.comboBox_TyreBrand = QtWidgets.QComboBox(Dialog)
        self.comboBox_TyreBrand.setGeometry(QtCore.QRect(260, 340, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_TyreBrand.setFont(font)
        self.comboBox_TyreBrand.setToolTip("")
        self.comboBox_TyreBrand.setStyleSheet("alternate-background-color: rgb(0, 170, 255);\n"
"gridline-color: rgb(0, 170, 255);")
        self.comboBox_TyreBrand.setObjectName("comboBox_TyreBrand")
        self.comboBox_TyreBrand.addItem("")
        self.comboBox_TyreBrand.addItem("")
        self.comboBox_TyreBrand.addItem("")
        self.comboBox_TyreBrand.addItem("")
        self.comboBox_TyreBrand.addItem("")
        self.comboBox_TyreBrand.addItem("")
        self.comboBox_TyreBrand.addItem("")
        self.comboBox_TyreBrand.addItem("")
        self.comboBox_TyreBrand.addItem("")
        self.comboBox_TyreBrand.addItem("")
        self.comboBox_TyreBrand.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 410, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("alternate-background-color: rgb(85, 170, 255);")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 410, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("alternate-background-color: rgb(85, 170, 255);")
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(590, 150, 441, 271))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(144)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 85, 0);\n"
"alternate-background-color: rgb(85, 85, 255);")
        self.label_14.setObjectName("label_14")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(260, 160, 211, 31))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # Conectar o botão "Cadastrar" ao método addPneu
        self.pushButton.clicked.connect(self.addPneu)

        # Configurar banco de dados
        self.setupDatabase()

        # Carregar placas
        self.loadPlates()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">CADASTRO DE PNEUS</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Placa:"))
        self.label_6.setText(_translate("Dialog", "DOT:"))
        self.label_9.setText(_translate("Dialog", "Posição pneu:"))
        self.label_10.setText(_translate("Dialog", "Sulcagem (mm):"))
        self.comboBoxTyrePos.setToolTip(_translate("Dialog", "Escolha uma entre as quatro opções disponíveis."))
        self.comboBoxTyrePos.setItemText(0, _translate("Dialog", "DE: Dianteiro esquerdo"))
        self.comboBoxTyrePos.setItemText(1, _translate("Dialog", "TE: Traseiro esquerdo"))
        self.comboBoxTyrePos.setItemText(2, _translate("Dialog", "TD: Traseiro direito"))
        self.comboBoxTyrePos.setItemText(3, _translate("Dialog", "DD: Dianteiro direito"))
        self.comboBoxTyrePos.setItemText(4, _translate("Dialog", "ES: Estepe"))
        self.comboBoxTyrePos.setItemText(5, _translate("Dialog", "LE: Leilão"))
        self.doubleSpinBoxTyreGroove.setToolTip(_translate("Dialog", "Esta medida pode ser feita com um paquímetro ou um profundímetro. A sulcagem pode variar ao longo da banda, então informe valor médio se necessário."))
        self.lineTyreDOT.setToolTip(_translate("Dialog", "Digite apenas números. Ex.: 2223."))
        self.lineTyreDOT.setPlaceholderText(_translate("Dialog", "Digite aqui"))
        self.pushButton.setWhatsThis(_translate("Dialog", "<html><head/><body><p>xxxxx</p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Cadastrar"))
        self.label_13.setText(_translate("Dialog", "Marca pneu:"))
        self.comboBox_TyreBrand.setItemText(0, _translate("Dialog", "Continental"))
        self.comboBox_TyreBrand.setItemText(1, _translate("Dialog", "Dunlop"))
        self.comboBox_TyreBrand.setItemText(2, _translate("Dialog", "Bridgestone"))
        self.comboBox_TyreBrand.setItemText(3, _translate("Dialog", "Dayton"))
        self.comboBox_TyreBrand.setItemText(4, _translate("Dialog", "Firestone"))
        self.comboBox_TyreBrand.setItemText(5, _translate("Dialog", "General tire"))
        self.comboBox_TyreBrand.setItemText(6, _translate("Dialog", "Goodyear"))
        self.comboBox_TyreBrand.setItemText(7, _translate("Dialog", "Hankook"))
        self.comboBox_TyreBrand.setItemText(8, _translate("Dialog", "Outro"))
        self.comboBox_TyreBrand.setItemText(9, _translate("Dialog", "Pirelli"))
        self.comboBox_TyreBrand.setItemText(10, _translate("Dialog", "Yokohama"))
        self.pushButton_2.setWhatsThis(_translate("Dialog", "<html><head/><body><p>xxxxx</p></body></html>"))
        self.pushButton_2.setText(_translate("Dialog", "Cancelar"))
        self.pushButton_3.setWhatsThis(_translate("Dialog", "<html><head/><body><p>xxxxx</p></body></html>"))
        self.pushButton_3.setText(_translate("Dialog", "Limpar"))
        self.label_14.setText(_translate("Dialog", "KL"))

    def setupDatabase(self):
        try:
            # Configura o banco de dados
            self.conn = conector.connect('pneusfrota.db')
            self.conn.execute('PRAGMA foreign_keys = on')
            self.cursor = self.conn.cursor()
        except conector.Error as e:
            QtWidgets.QMessageBox.critical(None, 'Erro', f'Erro ao conectar com o banco de dados: {e}')
            exit()

    def loadPlates(self):
        try:
            self.cursor.execute("SELECT Placa FROM Carro")
            placas = self.cursor.fetchall()
            for placa in placas:
                self.comboBox.addItem(placa[0])
        except conector.Error as e:
            QtWidgets.QMessageBox.critical(None, 'Erro', f'Erro ao carregar placas: {e}')

    def addPneu(self):
        # Coletar dados do formulário
        placa = self.comboBox.currentText()
        pos_pneu = self.comboBoxTyrePos.currentText()
        DOT = self.lineTyreDOT.text()
        sulcagem = self.doubleSpinBoxTyreGroove.value()
        marca_pneu = self.comboBox_TyreBrand.currentText()

        if placa and pos_pneu and DOT and sulcagem and marca_pneu:
            comando = "INSERT INTO Pneus (placa, pos_pneu, DOT, sulcagem, marca_pneu) VALUES (?, ?, ?, ?, ?)"
            try:
                self.cursor.execute(comando, (placa, pos_pneu, DOT, sulcagem, marca_pneu))
                self.conn.commit()
                QtWidgets.QMessageBox.information(None, 'Sucesso', 'Pneu cadastrado com sucesso!')
            except conector.IntegrityError as e:
                QtWidgets.QMessageBox.warning(None, 'Erro', f'Erro ao cadastrar o pneu: {e}')
            except conector.Error as e:
                QtWidgets.QMessageBox.critical(None, 'Erro', f'Erro no banco de dados: {e}')
            except Exception as e:
                QtWidgets.QMessageBox.critical(None, 'Erro', f'Ocorreu um erro inesperado: {e}')
        else:
            QtWidgets.QMessageBox.warning(None, 'Erro', 'Todos os campos são obrigatórios!')

    def closeEvent(self, event):
        # Fechar a conexão com o banco de dados ao fechar a janela
        self.conn.close()
        event.accept()
